### ISSUE TITLE
unable to download keyfile.

### ISSUE THREAD

**Issue by captainretro01** [tkbstudios/tinet-calc#27]
when i press download keyfile it responds "in development", how do I get online?

**Comment by code32123** [comment]
Same issue, following!

**Comment by tkbstudios** [comment]
The keyfile should be working soon, we need to have a proper way to store user credentials while also hold security and privacy as main point.
I am closing this issue because it will be hopefully released in the next major or minor update (will surely be released before V0.0.5 or with V0.0.5
